/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f20ae943-080c-45ce-b85c-a8589736b298",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_8UGQcaRdg",
    "aws_user_pools_web_client_id": "49af6hohj58ksj2cktgc5etiam",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "user",
            "endpoint": "https://3p6dbizux5.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users-dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
